name: No-Operation Workflow

on:
  push:
    branches:
      - main
      - l10n_main

env:
  LANG_CODE: "uk"

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    if: env.LANG_CODE == 'uk'
    steps:
      - name: No Operation
        run: echo "Hello World!"
