name: Test using variables

on:
  push:
    branches:
      - main
      - l10n_main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use the Variable
        run: echo "Variable value is ${{ secrets.LANG_CODE }}"
