name: No-Operation Workflow

on:
  push:
    branches:
      - main
      - l10n_main

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/l10n_main'
    steps:
      - name: No Operation
        run: echo "Hello World!"
