name: No-Operation Workflow

on:
  push:
    branches:
      - main
      - l10n_main

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: No Operation
        if: ${{ env.LANG_CODE == 'uk' }}
        run: echo "Hello World!"
