name: Test using variables

on:
  push:
    branches:
      - main
      - l10n_main

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      LANG_CODE: ${{ secrets.LANG_CODE || 'default_value' }}
    steps:
      - name: Use the Variable
        run: echo "Variable value is $LANG_CODE"
