name: No-Operation Workflow

on:
  push:
    branches:
      - main
      - l10n_main

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    env:
      LANG_CODE: ${{ secrets.LANG_CODE || 'en' }}
    steps:
      - name: No Operation
        run: echo "Hello $LANG_CODE!"
